import os
import json
from typing import List, Dict, Optional
from tavily import TavilyClient
from firecrawl import FirecrawlApp
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

class ToolManager:
    def __init__(self):
        # Initialize clients with error handling for missing keys
        try:
            self.tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))
        except Exception as e:
            print(f"Warning: Tavily client failed to init: {e}")
            self.tavily = None

        try:
            self.firecrawl = FirecrawlApp(api_key=os.getenv("FIRECRAWL_API_KEY"))
        except Exception as e:
            print(f"Warning: Firecrawl client failed to init: {e}")
            self.firecrawl = None

        try:
            url = os.getenv("SUPABASE_URL")
            key = os.getenv("SUPABASE_KEY")
            if url and key:
                self.supabase: Client = create_client(url, key)
            else:
                self.supabase = None
                print("Warning: Supabase credentials missing.")
        except Exception as e:
            print(f"Warning: Supabase client failed to init: {e}")
            self.supabase = None

    def search_tavily(self, query: str) -> List[Dict]:
        """Performs a web search using Tavily."""
        if not self.tavily:
            return [{"url": "error", "content": "Tavily API key missing."}]
        
        try:
            response = self.tavily.search(query=query, search_depth="basic")
            return response.get("results", [])
        except Exception as e:
            return [{"url": "error", "content": f"Search failed: {e}"}]

    def scrape_firecrawl(self, url: str) -> str:
        """Scrapes full markdown content from a URL using Firecrawl."""
        if not self.firecrawl:
            return "Firecrawl API key missing."
        
        try:
            scrape_result = self.firecrawl.scrape_url(url, params={'formats': ['markdown']})
            return scrape_result.get('markdown', '')
        except Exception as e:
            return f"Scraping failed: {e}"

    def check_memory(self, topic: str) -> Optional[dict]:
        """Checks Supabase for an existing report on the topic."""
        if not self.supabase:
            return None
        
        try:
            # Simple keyword match or exact match for now. 
            # In a real app, we might use vector search here.
            response = self.supabase.table("research_logs")\
                .select("*")\
                .ilike("topic", f"%{topic}%")\
                .execute()
            
            if response.data and len(response.data) > 0:
                # Return the most recent match
                return response.data[0]
            return None
        except Exception as e:
            print(f"Memory check failed: {e}")
            return None

    def save_memory(self, topic: str, content: str):
        """Saves the finished report to Supabase."""
        if not self.supabase:
            return
        
        try:
            data = {
                "topic": topic,
                "content": content
                # "created_at" is usually auto-generated by Supabase
            }
            self.supabase.table("research_logs").insert(data).execute()
        except Exception as e:
            print(f"Failed to save memory: {e}")
